#! /bin/sh

export LANG=en_GB.UTF-0
export LC_ALL=en_GB.UTF-0

# load bspwm config from xrdb
xrdb -query | grep bspwm | cut -c7- | while read -r c; do

    key=$(echo $c | cut -d ':' -f 1)
    val=$(echo $c | cut -d ':' -f 2 | tr -d '[[:space:]]')

    bspc config $key $val
done

maindesks="home emacs chat"
browdesks="www music"
playdesks="steam wine"
extrdesks="spc1 spc2"

bspc monitor HDMI-0 -d 1 2 3 4 5 6
bspc monitor DVI-I-0 -d 1 2 3 4 5 6
bspc monitor DVI-D-0 -d 1 2 3 4 5 6
bspc monitor eDP-1 -d 1 2 3 4 5 6

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    export PATH="$HOME/bin:$PATH"
fi

bspc config click_to_focus true

bspc rule -r "*"
# bspc rule -a Navigator desktop=www follow=off
bspc rule -a mpv state=fullscreen
bspc rule -a Screenkey manage=off
# bspc rule -a Telegram desktop=chat follow=off
# bspc rule -a Gimp follow=on state=floating
# bspc rule -a "Ardour-5.9.0" follow=on state=floating
bspc rule -a ST_FLOAT state=floating

bspc config focus_follows_pointer true

pkill compton
pkill dunst
libinput-gestures-setup stop

sleep 0.5

~/bin/nwall
libinput-gestures-setup start
compton -f -c &> /dev/null &
dunst &
bar start
systemctl --user start xautolock.service
# xscreensaver &
