#! /bin/sh

bspc config border_width 1
bspc config window_gap 25

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding 23
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config normal_border_color "#333333"
bspc config focused_border_color "#eeeeee"
bspc config presel_border_color "#FF8888"

maindesks="home emacs"
browdesks="www music"
playdesks="steam wine"
extrdesks="spc1 spc2"

bspc monitor DVI-I-1 -d $maindesks $playdesks
bspc monitor DVI-D-0 -d $browdesks
bspc monitor LVDS1 -d $maindesks $browdesks

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    export PATH="$HOME/bin:$PATH"
fi

#~/.config/panel/panel &
# ~/.fehbg &
#sudo xboxdrv --detach-kernel-driver --mimic-xpad &
hsetroot -solid "#335566"
compton -f -c &
tint2 &
