#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

export EMAIL="northcode.no@gmail.com"
export NAME="Andreas Larsen"
export SMTPSERVER="smtp.gmail.com"

export XDG_RUNTIME_DIR="/run/user/$UID"
export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"

if test $(hostname) == "andreas-l0"
then
	xrandr --setprovideroutputsource modesetting NVIDIA-0
	xrandr --auto
fi

xrdb ~/.config/X/resources

# enable tap to click for touchpad
xinput set-prop 12 273 1

setxkbmap no
setxkbmap -option caps:escape
xset r rate 200 70
#xmodmap ~/.config/X/modmap
sxhkd &
bspwm
