#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

export EMAIL="northcode.no@gmail.com"
export NAME="Andreas Larsen"
export SMTPSERVER="smtp.gmail.com"

export XDG_RUNTIME_DIR="/run/user/$UID"
export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
xrdb ~/.config/X/resources

touchpad_id=$(xinput list --short | grep -i touchpad | cut -f 2 | cut -d = -f 2)
xinput set-prop $touchpad_id "libinput Tapping Enabled" 1
xinput set-prop $touchpad_id "libinput Natural Scrolling Enabled" 1

setxkbmap no
setxkbmap -option caps:escape
xset r rate 200 70
#xmodmap ~/.config/X/modmap
# light-locker &ght -S 
xscreensaver &
sxhkd &
bspwm
