#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

export EMAIL="northcode.no@gmail.com"
export NAME="Andreas Larsen"
export SMTPSERVER="smtp.gmail.com"

xrdb ~/.config/X/resources
setxkbmap no
xmodmap ~/.config/X/modmap
sxhkd &
bspwm
